build: false


environment:
  matrix:
    - PYTHON_VERSION: "2.7"
      PYTHON:         "C:\\Miniconda"
      MINICONDA:      "C:\\Miniconda"
      PYTHON_ARCH:    "32"

    - PYTHON_VERSION: "2.7"
      PYTHON:         "C:\\Miniconda-x64"
      MINICONDA:      "C:\\Miniconda-x64"
      PYTHON_ARCH:    "64"

    - PYTHON_VERSION: "3.6"
      PYTHON:         "C:\\Miniconda36"
      MINICONDA:      "C:\\Miniconda36"
      PYTHON_ARCH:    "32"

    - PYTHON_VERSION: "3.6"
      PYTHON:         "C:\\Miniconda36-x64"
      MINICONDA:      "C:\\Miniconda36-x64"
      PYTHON_ARCH:    "64"

    - PYTHON_VERSION: "3.7"
      PYTHON:         "C:\\Miniconda37"
      MINICONDA:      "C:\\Miniconda37"
      PYTHON_ARCH:    "32"

    - PYTHON_VERSION: "3.7"
      PYTHON:         "C:\\Miniconda37-x64"
      MINICONDA:      "C:\\Miniconda37-x64"
      PYTHON_ARCH:    "64"

    - PYTHON_VERSION: "3.8"
      PYTHON:         "C:\\Miniconda37"
      MINICONDA:      "C:\\Miniconda37"
      PYTHON_ARCH:    "32"

    - PYTHON_VERSION: "3.8"
      PYTHON:         "C:\\Miniconda37-x64"
      MINICONDA:      "C:\\Miniconda37-x64"
      PYTHON_ARCH:    "64"




install:
  - "set PATH=%MINICONDA%;%MINICONDA%\\Scripts;%PATH%"
  - conda update  --yes -q conda
  - conda create  --yes -n test_env python=%PYTHON_VERSION%
  - activate test_env
  - conda install --yes cython numpy zlib six pytest coverage pytest-cov
  - conda update --yes pytest
  - set ZLIB_HOME=%CONDA_PREFIX%\\Library
  - python setup.py develop


test_script:
  - pytest -v -s -m indexed_gzip_test          --niters 250
  - pytest -v -s -m indexed_gzip_test --concat --niters 250
